apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-mode: auto
  labels:
    app: http-server
  name: http-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http-server
